**Importación y Carga de Librerias**

In [2]:
import pandas as pd
import numpy as np

**Carga de Datos y Análisis**

→ Para datos de 'homicidios'

In [3]:
# Carga de los datos del archivo 'homicidios' del apartado 'hechos' y visualización de los mismos
df_homicidios_hechos = pd.read_excel('homicidios.xlsx',sheet_name = 'HECHOS')
df_homicidios_hechos

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,HH,LUGAR_DEL_HECHO,TIPO_DE_CALLE,...,Altura,Cruce,Dirección Normalizada,COMUNA,XY (CABA),pos x,pos y,PARTICIPANTES,VICTIMA,ACUSADO
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,4,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,...,NaN,"FERNANDEZ DE LA CRUZ, F., GRAL. AV.","PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...",8,Point (98896.78238426 93532.43437792),-58.47533969,-34.68757022,MOTO-AUTO,MOTO,AUTO
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,1,AV GRAL PAZ Y AV DE LOS CORRALES,GRAL PAZ,...,NaN,DE LOS CORRALES AV.,"PAZ, GRAL. AV. y DE LOS CORRALES AV.",9,Point (95832.05571093 95505.41641999),-58.50877521,-34.66977709,AUTO-PASAJEROS,AUTO,PASAJEROS
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,7,AV ENTRE RIOS 2034,AVENIDA,...,2034.0,NaN,ENTRE RIOS AV. 2034,1,Point (106684.29090040 99706.57687843),-58.39040293,-34.63189362,MOTO-AUTO,MOTO,AUTO
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,0,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,...,NaN,"VILLEGAS, CONRADO, GRAL.","LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.",8,Point (99840.65224780 94269.16534422),-58.46503904,-34.68092974,MOTO-SD,MOTO,SD
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,5,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,...,NaN,"SAENZ PE?A, LUIS, PRES.","SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.",1,Point (106980.32827929 100752.16915795),-58.38718297,-34.62246630,MOTO-PASAJEROS,MOTO,PASAJEROS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,2021-0093,1,2021-12-13,2021,12,13,17:10:00,17,AV. RIESTRA Y MOM,AVENIDA,...,NaN,MOM,RIESTRA AV. y MOM,7,Point (102728.60090138 98186.24929177),-58.43353773,-34.64561636,MOTO-AUTO,MOTO,AUTO
692,2021-0094,1,2021-12-20,2021,12,20,01:10:00,1,AU DELLEPIANE Y LACARRA,AUTOPISTA,...,NaN,LACARRA AV.,"DELLEPIANE, LUIS, TTE. GRAL. y LACARRA AV.",9,Point (99624.29795829 97569.69801131),-58.46739825,-34.65117757,MOTO-AUTO,MOTO,AUTO
693,2021-0095,1,2021-12-30,2021,12,30,00:43:00,0,AV. GAONA Y TERRADA,AVENIDA,...,NaN,TERRADA,GAONA AV. y TERRADA,11,Point (99116.45492358 101045.23284826),-58.47293407,-34.61984745,MOTO-CARGAS,MOTO,CARGAS
694,2021-0096,1,2021-12-15,2021,12,15,10:30:00,10,AV. EVA PERON 4071,AVENIDA,...,4071.0,NaN,"PERON, EVA AV. 4071",9,Point (99324.54463985 97676.26932409),-58.47066794,-34.65021673,AUTO-CARGAS,AUTO,CARGAS
695,2021-0097,1,2021-11-18,2021,11,18,06:10:00,6,PADRE CARLOS MUJICA 709,CALLE,...,709.0,NaN,PADRE CARLOS MUGICA 709,1,Point (107664.16647795 104708.63962087),-58.37976155,-34.58679619,BICICLETA-AUTO,BICICLETA,AUTO

In [4]:
# Visualización del tipo de datos
df_homicidios_hechos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 696 entries, 0 to 695
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     696 non-null    object
 1   N_VICTIMAS             696 non-null    int64
 2   FECHA                  696 non-null    datetime64[ns]
 3   AAAA                   696 non-null    int64
 4   MM                     696 non-null    int64
 5   DD                     696 non-null    int64
 6   HORA                   696 non-null    object
 7   HH                     696 non-null    object
 8   LUGAR_DEL_HECHO        696 non-null    object
 9   TIPO_DE_CALLE          696 non-null    object
 10  Calle                  695 non-null    object
 11  Altura                 129 non-null    float64
 12  Cruce                  525 non-null    object
 13  Dirección Normalizada  688 non-null    object
 14  COMUNA                 696 non-null    int64
 15  XY (CABA)              696 non-null    object
 16  pos x                  696 non-null    object
 17  pos y                  696 non-null    object
 18  PARTICIPANTES          696 non-null    object
 19  VICTIMA                696 non-null    object
 20  ACUSADO                696 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(5), object(14)
memory usage: 114.3+ KB

In [5]:
# Convertimos los datos a minusculas
df_homicidios_hechos = df_homicidios_hechos.applymap(lambda x: x.lower() if isinstance(x, str) else x)

# Convertimos los titulos de las columnas a minusculas
df_homicidios_hechos.columns = df_homicidios_hechos.columns.str.lower()

C:\Users\nacho\AppData\Local\Temp\ipykernel_4472\1574284483.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_homicidios_hechos = df_homicidios_hechos.applymap(lambda x: x.lower() if isinstance(x, str) else x)

In [10]:
# Identificamos duplicados en las columnas
duplicates_hechos = df_homicidios_hechos[df_homicidios_hechos.duplicated(subset=['id', 'n_victimas', 'fecha', 'aaaa', 'mm', 'dd', 'hora', 'hh',
       'lugar_del_hecho', 'tipo_de_calle', 'calle', 'altura', 'cruce',
       'dirección normalizada', 'comuna', 'xy (caba)', 'pos x', 'pos y',
       'participantes', 'victima', 'acusado'])]

# Mostramos los datos duplicados
print(duplicates_hechos)

Empty DataFrame
Columns: [id, n_victimas, fecha, aaaa, mm, dd, hora, hh, lugar_del_hecho, tipo_de_calle, calle, altura, cruce, dirección normalizada, comuna, xy (caba), pos x, pos y, participantes, victima, acusado]
Index: []

[0 rows x 21 columns]

In [11]:
# Verificamos valores nulos
nules_hechos = df_homicidios_hechos.isnull().any()

# Mostramos los valores nulos
print(nules_hechos)

id                       False
n_victimas               False
fecha                    False
aaaa                     False
mm                       False
dd                       False
hora                     False
hh                       False
lugar_del_hecho          False
tipo_de_calle            False
calle                     True
altura                    True
cruce                     True
dirección normalizada     True
comuna                   False
xy (caba)                False
pos x                    False
pos y                    False
participantes            False
victima                  False
acusado                  False
dtype: bool

In [17]:
# Eliminamos los nulos
df_homicidios_hechos.dropna(how='all', inplace=True)

In [18]:
# Cambiamos el tipo de dato de la columna 'altura'
df_homicidios_hechos['altura'] = df_homicidios_hechos['altura'].astype('object')

# Visualizamos el cambio
print(df_homicidios_hechos['altura'].dtype)

object

In [19]:
# Reemplazamos los datos nulos por 'sd'
df_homicidios_hechos = df_homicidios_hechos.fillna(value='sd')

# Visualizamos los datos
df_homicidios_hechos

,id,n_victimas,fecha,aaaa,mm,dd,hora,hh,lugar_del_hecho,tipo_de_calle,...,altura,cruce,dirección normalizada,comuna,xy (caba),pos x,pos y,participantes,victima,acusado
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,4,av piedra buena y av fernandez de la cruz,avenida,...,sd,"fernandez de la cruz, f., gral. av.","piedra buena av. y fernandez de la cruz, f., g...",8,point (98896.78238426 93532.43437792),-58.47533969,-34.68757022,moto-auto,moto,auto
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,1,av gral paz y av de los corrales,gral paz,...,sd,de los corrales av.,"paz, gral. av. y de los corrales av.",9,point (95832.05571093 95505.41641999),-58.50877521,-34.66977709,auto-pasajeros,auto,pasajeros
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,7,av entre rios 2034,avenida,...,2034.0,sd,entre rios av. 2034,1,point (106684.29090040 99706.57687843),-58.39040293,-34.63189362,moto-auto,moto,auto
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,0,av larrazabal y gral villegas conrado,avenida,...,sd,"villegas, conrado, gral.","larrazabal av. y villegas, conrado, gral.",8,point (99840.65224780 94269.16534422),-58.46503904,-34.68092974,moto-sd,moto,sd
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,5,av san juan y presidente luis saenz peña,avenida,...,sd,"saenz pe?a, luis, pres.","san juan av. y saenz peã‘a, luis, pres.",1,point (106980.32827929 100752.16915795),-58.38718297,-34.62246630,moto-pasajeros,moto,pasajeros
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,2021-0093,1,2021-12-13,2021,12,13,17:10:00,17,av. riestra y mom,avenida,...,sd,mom,riestra av. y mom,7,point (102728.60090138 98186.24929177),-58.43353773,-34.64561636,moto-auto,moto,auto
692,2021-0094,1,2021-12-20,2021,12,20,01:10:00,1,au dellepiane y lacarra,autopista,...,sd,lacarra av.,"dellepiane, luis, tte. gral. y lacarra av.",9,point (99624.29795829 97569.69801131),-58.46739825,-34.65117757,moto-auto,moto,auto
693,2021-0095,1,2021-12-30,2021,12,30,00:43:00,0,av. gaona y terrada,avenida,...,sd,terrada,gaona av. y terrada,11,point (99116.45492358 101045.23284826),-58.47293407,-34.61984745,moto-cargas,moto,cargas
694,2021-0096,1,2021-12-15,2021,12,15,10:30:00,10,av. eva peron 4071,avenida,...,4071.0,sd,"peron, eva av. 4071",9,point (99324.54463985 97676.26932409),-58.47066794,-34.65021673,auto-cargas,auto,cargas
695,2021-0097,1,2021-11-18,2021,11,18,06:10:00,6,padre carlos mujica 709,calle,...,709.0,sd,padre carlos mugica 709,1,point (107664.16647795 104708.63962087),-58.37976155,-34.58679619,bicicleta-auto,bicicleta,auto

In [20]:
# Convertimos el DF - df_homicidios_hechos a un CSV, y lo exportamos
df_homicidios_hechos.to_csv('../EDA/homicidios_hechos.csv', index=False)

In [6]:
# Carga de los datos del archivo 'homicidios' del apartado 'victimas' y visualización de los mismos
df_homicidios_victimas = pd.read_excel('homicidios.xlsx',sheet_name = 'VICTIMAS')
df_homicidios_victimas

,ID_hecho,FECHA,AAAA,MM,DD,ROL,VICTIMA,SEXO,EDAD,FECHA_FALLECIMIENTO
0,2016-0001,2016-01-01,2016,1,1,CONDUCTOR,MOTO,MASCULINO,19,2016-01-01 00:00:00
1,2016-0002,2016-01-02,2016,1,2,CONDUCTOR,AUTO,MASCULINO,70,2016-01-02 00:00:00
2,2016-0003,2016-01-03,2016,1,3,CONDUCTOR,MOTO,MASCULINO,30,2016-01-03 00:00:00
3,2016-0004,2016-01-10,2016,1,10,CONDUCTOR,MOTO,MASCULINO,18,SD
4,2016-0005,2016-01-21,2016,1,21,CONDUCTOR,MOTO,MASCULINO,29,2016-02-01 00:00:00
...,...,...,...,...,...,...,...,...,...,...
712,2021-0092,2021-12-12,2021,12,12,PEATON,PEATON,FEMENINO,50,2021-12-12 00:00:00
713,2021-0093,2021-12-13,2021,12,13,PASAJERO_ACOMPAÑANTE,MOTO,FEMENINO,18,2021-12-18 00:00:00
714,2021-0094,2021-12-20,2021,12,20,PASAJERO_ACOMPAÑANTE,MOTO,FEMENINO,43,2021-12-20 00:00:00
715,2021-0095,2021-12-30,2021,12,30,CONDUCTOR,MOTO,MASCULINO,27,2022-01-02 00:00:00
716,2021-0096,2021-12-15,2021,12,15,CONDUCTOR,AUTO,MASCULINO,60,2021-12-20 00:00:00

In [7]:
# Visualización del tipo de datos
df_homicidios_victimas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 717 entries, 0 to 716
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID_hecho             717 non-null    object
 1   FECHA                717 non-null    datetime64[ns]
 2   AAAA                 717 non-null    int64
 3   MM                   717 non-null    int64
 4   DD                   717 non-null    int64
 5   ROL                  717 non-null    object
 6   VICTIMA              717 non-null    object
 7   SEXO                 717 non-null    object
 8   EDAD                 717 non-null    object
 9   FECHA_FALLECIMIENTO  717 non-null    object
dtypes: datetime64[ns](1), int64(3), object(6)
memory usage: 56.1+ KB

In [8]:
# Convertimos los datos a minusculas
df_homicidios_victimas = df_homicidios_victimas.applymap(lambda x: x.lower() if isinstance(x, str) else x)

# Convertimos los titulos de las columnas a minusculas
df_homicidios_victimas.columns = df_homicidios_victimas.columns.str.lower()

C:\Users\nacho\AppData\Local\Temp\ipykernel_4472\4077978155.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_homicidios_victimas = df_homicidios_victimas.applymap(lambda x: x.lower() if isinstance(x, str) else x)

In [14]:
# Identificamos duplicados en las columnas
duplicates_victimas = df_homicidios_victimas[df_homicidios_victimas.duplicated(subset=['id_hecho', 'fecha', 'aaaa', 'mm', 'dd', 'rol', 'victima', 'sexo',
       'edad', 'fecha_fallecimiento'])]

# Mostramos los datos duplicados
print(duplicates_victimas)

Empty DataFrame
Columns: [id_hecho, fecha, aaaa, mm, dd, rol, victima, sexo, edad, fecha_fallecimiento]
Index: []

In [15]:
# Verificamos valores nulos
nules_victimas = df_homicidios_victimas.isnull().any()

# Mostramos los valores nulos
print(nules_victimas)

id_hecho               False
fecha                  False
aaaa                   False
mm                     False
dd                     False
rol                    False
victima                False
sexo                   False
edad                   False
fecha_fallecimiento    False
dtype: bool

In [21]:
# Convertimos el DF - df_homicidios_victimas a un CSV, y lo exportamos
df_homicidios_victimas.to_csv('../EDA/homicidios_victimas.csv', index=False)

→ Para datos de 'lesiones'

In [22]:
# Carga de los datos del archivo 'homicidios' y visualización de los mismos
df_lesiones = pd.read_excel('lesiones.xlsx', engine='openpyxl')
df_lesiones

,id,n_victimas,aaaa,mm,dd,fecha,hora,franja_hora,direccion_normalizada,comuna,...,latutid,victima,acusado,participantes,moto,auto,transporte_publico,camion,ciclista,gravedad
0,LC-2019-0000179,1,2019,1,1,2019-01-01 00:00:00,09:00:00,9,SD,14,...,-34.559658,CICLISTA,SD,CICLISTA-SD,SD,SD,SD,SD,x,SD
1,LC-2019-0000053,1,2019,1,1,2019-01-01 00:00:00,01:55:00,1,SD,8,...,-34.669125,AUTO,SD,AUTO-SD,SD,x,SD,SD,SD,SD
2,LC-2019-0000063,1,2019,1,1,2019-01-01 00:00:00,02:00:00,2,SD,8,...,-34.677556,SD,SD,SD-SD,SD,SD,SD,SD,SD,SD
3,LC-2019-0000079,1,2019,1,1,2019-01-01 00:00:00,02:30:00,2,SD,7,...,-34.647349,PEATON,SD,PEATON-SD,x,SD,SD,SD,SD,SD
4,LC-2019-0000082,4,2019,1,1,2019-01-01 00:00:00,04:30:00,4,SD,3,...,-34.604579,AUTO,SD,AUTO-SD,SD,SD,x,SD,SD,SD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23780,LC-2021-0652849,1,2021,12,31,2021-12-31 00:00:00,19:30:00,19,"ALBERDI, JUAN BAUTISTA AV. y GUAMINI",9,...,-34.659713573880,SD,SD,SD-SD,SD,SD,SD,SD,SD,SD
23781,LC-2021-0652865,2,2021,12,31,2021-12-31 00:00:00,19:40:00,19,"ALBERDI, JUAN BAUTISTA AV. 4436",9,...,-34.641753304864,SD,SD,SD-SD,SD,SD,SD,SD,SD,SD
23782,LC-2021-0652907,1,2021,12,31,2021-12-31 00:00:00,20:00:00,20,SD,1,...,-34.583083,SD,SD,SD-SD,SD,SD,SD,SD,SD,SD
23783,LC-2021-0652921,1,2021,12,31,2021-12-31 00:00:00,22:00:00,22,LINIERS VIRREY y MORENO,5,...,-34.614288229345,MOTO,TRANSPORTE PUBLICO,MOTO-TRANSPORTE PUBLICO,x,0,x,0,0,GRAVE
23784,LC-2020-0244615,1,2020,5,17,5/17/2020,21:00:00,21,SD,SD,...,-3472890716,MOTO,AUTO,MOTO-AUTO,x,x,0,0,0,SD

In [23]:
# Visualización del tipo de datos
df_lesiones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23785 entries, 0 to 23784
Data columns (total 27 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     23785 non-null  object
 1   n_victimas             23785 non-null  int64
 2   aaaa                   23785 non-null  int64
 3   mm                     23785 non-null  int64
 4   dd                     23785 non-null  int64
 5   fecha                  23785 non-null  object
 6   hora                   23785 non-null  object
 7   franja_hora            23780 non-null  object
 8   direccion_normalizada  23732 non-null  object
 9   comuna                 23616 non-null  object
 10  tipo_calle             23785 non-null  object
 11  otra_direccion         23785 non-null  object
 12  calle                  12867 non-null  object
 13  altura                 12771 non-null  float64
 14  cruce                  9407 non-null   object
 15  geocodificacion_CABA   23746 non-null  object
 16  longitud               23523 non-null  object
 17  latutid                23523 non-null  object
 18  victima                23785 non-null  object
 19  acusado                23785 non-null  object
 20  participantes          23785 non-null  object
 21  moto                   23692 non-null  object
 22  auto                   23692 non-null  object
 23  transporte_publico     23692 non-null  object
 24  camion                 23692 non-null  object
 25  ciclista               23692 non-null  object
 26  gravedad               23785 non-null  object
dtypes: float64(1), int64(4), object(22)
memory usage: 4.9+ MB

In [24]:
# Convertimos los datos a minusculas
df_lesiones = df_lesiones.applymap(lambda x: x.lower() if isinstance(x, str) else x)

# Convertimos los titulos de las columnas a minusculas
df_lesiones.columns = df_lesiones.columns.str.lower()

C:\Users\nacho\AppData\Local\Temp\ipykernel_4472\1939685612.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_lesiones = df_lesiones.applymap(lambda x: x.lower() if isinstance(x, str) else x)

In [25]:
# Identificamos duplicados en las columnas
duplicates_lesiones = df_lesiones[df_lesiones.duplicated(subset=['id', 'n_victimas', 'aaaa', 'mm', 'dd', 'fecha', 'hora', 'franja_hora',
       'direccion_normalizada', 'comuna', 'tipo_calle', 'otra_direccion',
       'calle', 'altura', 'cruce', 'geocodificacion_caba', 'longitud',
       'latutid', 'victima', 'acusado', 'participantes', 'moto', 'auto',
       'transporte_publico', 'camion', 'ciclista', 'gravedad'])]

# Mostramos los datos duplicados
print(duplicates_lesiones)

Empty DataFrame
Columns: [id, n_victimas, aaaa, mm, dd, fecha, hora, franja_hora, direccion_normalizada, comuna, tipo_calle, otra_direccion, calle, altura, cruce, geocodificacion_caba, longitud, latutid, victima, acusado, participantes, moto, auto, transporte_publico, camion, ciclista, gravedad]
Index: []

[0 rows x 27 columns]

In [26]:
# Verificamos valores nulos
nules_lesiones = df_lesiones.isnull().any()

# Mostramos los valores nulos
print(nules_lesiones)

id                       False
n_victimas               False
aaaa                     False
mm                       False
dd                       False
fecha                    False
hora                     False
franja_hora               True
direccion_normalizada     True
comuna                    True
tipo_calle               False
otra_direccion           False
calle                     True
altura                    True
cruce                     True
geocodificacion_caba      True
longitud                  True
latutid                   True
victima                  False
acusado                  False
participantes            False
moto                      True
auto                      True
transporte_publico        True
camion                    True
ciclista                  True
gravedad                 False
dtype: bool

In [27]:
# Eliminamos los nulos
df_lesiones.dropna(how='all', inplace=True)

In [28]:
# Cambiamos el tipo de dato de la columna 'altura'
df_lesiones['altura'] = df_lesiones['altura'].astype('object')

# Visualizamos el cambio
print(df_lesiones['altura'].dtype)

object

In [29]:
# Reemplazamos los datos nulos por 'sd'
df_lesiones = df_lesiones.fillna(value='sd')

# Visualizamos los datos
df_lesiones

,id,n_victimas,aaaa,mm,dd,fecha,hora,franja_hora,direccion_normalizada,comuna,...,latutid,victima,acusado,participantes,moto,auto,transporte_publico,camion,ciclista,gravedad
0,lc-2019-0000179,1,2019,1,1,2019-01-01 00:00:00,09:00:00,9,sd,14,...,-34.559658,ciclista,sd,ciclista-sd,sd,sd,sd,sd,x,sd
1,lc-2019-0000053,1,2019,1,1,2019-01-01 00:00:00,01:55:00,1,sd,8,...,-34.669125,auto,sd,auto-sd,sd,x,sd,sd,sd,sd
2,lc-2019-0000063,1,2019,1,1,2019-01-01 00:00:00,02:00:00,2,sd,8,...,-34.677556,sd,sd,sd-sd,sd,sd,sd,sd,sd,sd
3,lc-2019-0000079,1,2019,1,1,2019-01-01 00:00:00,02:30:00,2,sd,7,...,-34.647349,peaton,sd,peaton-sd,x,sd,sd,sd,sd,sd
4,lc-2019-0000082,4,2019,1,1,2019-01-01 00:00:00,04:30:00,4,sd,3,...,-34.604579,auto,sd,auto-sd,sd,sd,x,sd,sd,sd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23780,lc-2021-0652849,1,2021,12,31,2021-12-31 00:00:00,19:30:00,19,"alberdi, juan bautista av. y guamini",9,...,-34.659713573880,sd,sd,sd-sd,sd,sd,sd,sd,sd,sd
23781,lc-2021-0652865,2,2021,12,31,2021-12-31 00:00:00,19:40:00,19,"alberdi, juan bautista av. 4436",9,...,-34.641753304864,sd,sd,sd-sd,sd,sd,sd,sd,sd,sd
23782,lc-2021-0652907,1,2021,12,31,2021-12-31 00:00:00,20:00:00,20,sd,1,...,-34.583083,sd,sd,sd-sd,sd,sd,sd,sd,sd,sd
23783,lc-2021-0652921,1,2021,12,31,2021-12-31 00:00:00,22:00:00,22,liniers virrey y moreno,5,...,-34.614288229345,moto,transporte publico,moto-transporte publico,x,0,x,0,0,grave
23784,lc-2020-0244615,1,2020,5,17,5/17/2020,21:00:00,21,sd,sd,...,-3472890716,moto,auto,moto-auto,x,x,0,0,0,sd

In [30]:
# Convertimos el DF - df_homicidios a un CSV, y lo exportamos
df_lesiones.to_csv('../EDA/lesiones_clean.csv', index=False)